services:
  - type: web
    name: gofood-backend
    runtime: node
    plan: free
    rootDir: Gofood/backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: OPENCAGE_API_KEY
        sync: false
